project_id = "xnkhnelsuzhdzylzywbq"

[functions.accounting-assistant]
verify_jwt = false

[functions.provision-tenant]
verify_jwt = false

[functions.expire-subscriptions]
verify_jwt = false

[functions.send-invitation]
verify_jwt = false

[functions.accept-invitation]
verify_jwt = false

[functions.restore-subscriber]
verify_jwt = false

[functions.delete-subscriber]
verify_jwt = false

[functions.reset-usage]
verify_jwt = false

