ALTER TABLE public.accounts ADD CONSTRAINT accounts_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.accounts ADD CONSTRAINT accounts_cost_center_id_fkey FOREIGN KEY (cost_center_id) REFERENCES public.cost_centers(id) ON DELETE SET NULL;
ALTER TABLE public.accounts ADD CONSTRAINT accounts_global_account_id_fkey FOREIGN KEY (global_account_id) REFERENCES public.global_accounts(id) ON DELETE SET NULL;
ALTER TABLE public.accounts ADD CONSTRAINT accounts_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.appointments ADD CONSTRAINT appointments_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.appointments ADD CONSTRAINT appointments_doctor_id_fkey FOREIGN KEY (doctor_id) REFERENCES public.doctors(id) ON DELETE CASCADE;
ALTER TABLE public.appointments ADD CONSTRAINT appointments_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id) ON DELETE CASCADE;
ALTER TABLE public.asset_categories ADD CONSTRAINT asset_categories_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.asset_depreciation_entries ADD CONSTRAINT asset_depreciation_entries_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES public.fixed_assets(id) ON DELETE CASCADE;
ALTER TABLE public.asset_depreciation_entries ADD CONSTRAINT asset_depreciation_entries_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.asset_depreciation_entries ADD CONSTRAINT asset_depreciation_entries_journal_entry_id_fkey FOREIGN KEY (journal_entry_id) REFERENCES public.journal_entries(id) ON DELETE SET NULL;
ALTER TABLE public.asset_maintenance_records ADD CONSTRAINT asset_maintenance_records_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES public.fixed_assets(id) ON DELETE CASCADE;
ALTER TABLE public.asset_maintenance_records ADD CONSTRAINT asset_maintenance_records_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.audit_logs ADD CONSTRAINT audit_logs_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE SET NULL;
ALTER TABLE public.bank_accounts ADD CONSTRAINT bank_accounts_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.bank_accounts ADD CONSTRAINT bank_accounts_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.bill_of_materials ADD CONSTRAINT bill_of_materials_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.bill_of_materials ADD CONSTRAINT bill_of_materials_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;
ALTER TABLE public.bom_items ADD CONSTRAINT bom_items_bom_id_fkey FOREIGN KEY (bom_id) REFERENCES public.bill_of_materials(id) ON DELETE CASCADE;
ALTER TABLE public.bom_items ADD CONSTRAINT bom_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;
ALTER TABLE public.bom_items ADD CONSTRAINT bom_items_unit_id_fkey FOREIGN KEY (unit_id) REFERENCES public.units(id) ON DELETE CASCADE;
ALTER TABLE public.branch_account_settings ADD CONSTRAINT branch_account_settings_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id) ON DELETE SET NULL;
ALTER TABLE public.branch_account_settings ADD CONSTRAINT branch_account_settings_cogs_account_id_fkey FOREIGN KEY (cogs_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.branch_account_settings ADD CONSTRAINT branch_account_settings_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.branch_account_settings ADD CONSTRAINT branch_account_settings_consumption_expense_account_id_fkey FOREIGN KEY (consumption_expense_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.branch_account_settings ADD CONSTRAINT branch_account_settings_inventory_account_id_fkey FOREIGN KEY (inventory_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.branch_account_settings ADD CONSTRAINT branch_account_settings_inventory_gain_account_id_fkey FOREIGN KEY (inventory_gain_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.branch_account_settings ADD CONSTRAINT branch_account_settings_inventory_loss_account_id_fkey FOREIGN KEY (inventory_loss_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.branch_account_settings ADD CONSTRAINT branch_account_settings_purchase_discount_account_id_fkey FOREIGN KEY (purchase_discount_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.branch_account_settings ADD CONSTRAINT branch_account_settings_purchase_expense_account_id_fkey FOREIGN KEY (purchase_expense_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.branch_account_settings ADD CONSTRAINT branch_account_settings_purchase_payable_account_id_fkey FOREIGN KEY (purchase_payable_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.branch_account_settings ADD CONSTRAINT branch_account_settings_purchase_tax_account_id_fkey FOREIGN KEY (purchase_tax_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.branch_account_settings ADD CONSTRAINT branch_account_settings_sales_discount_account_id_fkey FOREIGN KEY (sales_discount_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.branch_account_settings ADD CONSTRAINT branch_account_settings_sales_receivable_account_id_fkey FOREIGN KEY (sales_receivable_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.branch_account_settings ADD CONSTRAINT branch_account_settings_sales_revenue_account_id_fkey FOREIGN KEY (sales_revenue_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.branch_account_settings ADD CONSTRAINT branch_account_settings_sales_tax_account_id_fkey FOREIGN KEY (sales_tax_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.branch_account_settings ADD CONSTRAINT branch_account_settings_wip_account_id_fkey FOREIGN KEY (wip_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.branch_payment_methods ADD CONSTRAINT branch_payment_methods_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id) ON DELETE SET NULL;
ALTER TABLE public.branch_payment_methods ADD CONSTRAINT branch_payment_methods_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.branch_payment_methods ADD CONSTRAINT branch_payment_methods_payment_method_id_fkey FOREIGN KEY (payment_method_id) REFERENCES public.payment_methods(id) ON DELETE CASCADE;
ALTER TABLE public.branches ADD CONSTRAINT branches_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.car_brands ADD CONSTRAINT car_brands_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.car_models ADD CONSTRAINT car_models_brand_id_fkey FOREIGN KEY (brand_id) REFERENCES public.car_brands(id) ON DELETE CASCADE;
ALTER TABLE public.car_models ADD CONSTRAINT car_models_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.client_screens ADD CONSTRAINT client_screens_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.client_screens ADD CONSTRAINT client_screens_screen_id_fkey FOREIGN KEY (screen_id) REFERENCES public.system_screens(id) ON DELETE CASCADE;
ALTER TABLE public.clinic_account_settings ADD CONSTRAINT clinic_account_settings_bank_account_id_fkey FOREIGN KEY (bank_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.clinic_account_settings ADD CONSTRAINT clinic_account_settings_cash_account_id_fkey FOREIGN KEY (cash_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.clinic_account_settings ADD CONSTRAINT clinic_account_settings_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.clinic_account_settings ADD CONSTRAINT clinic_account_settings_insurance_receivable_account_id_fkey FOREIGN KEY (insurance_receivable_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.clinic_account_settings ADD CONSTRAINT clinic_account_settings_medical_revenue_account_id_fkey FOREIGN KEY (medical_revenue_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.clinic_account_settings ADD CONSTRAINT clinic_account_settings_patient_receivable_account_id_fkey FOREIGN KEY (patient_receivable_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.clinic_invoice_items ADD CONSTRAINT clinic_invoice_items_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.clinic_invoices(id) ON DELETE CASCADE;
ALTER TABLE public.clinic_invoices ADD CONSTRAINT clinic_invoices_appointment_id_fkey FOREIGN KEY (appointment_id) REFERENCES public.appointments(id) ON DELETE CASCADE;
ALTER TABLE public.clinic_invoices ADD CONSTRAINT clinic_invoices_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.clinic_invoices ADD CONSTRAINT clinic_invoices_doctor_id_fkey FOREIGN KEY (doctor_id) REFERENCES public.doctors(id) ON DELETE CASCADE;
ALTER TABLE public.clinic_invoices ADD CONSTRAINT clinic_invoices_journal_entry_id_fkey FOREIGN KEY (journal_entry_id) REFERENCES public.journal_entries(id) ON DELETE SET NULL;
ALTER TABLE public.clinic_invoices ADD CONSTRAINT clinic_invoices_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id) ON DELETE CASCADE;
ALTER TABLE public.company_feature_overrides ADD CONSTRAINT company_feature_overrides_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.company_members ADD CONSTRAINT company_members_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.company_permission_overrides ADD CONSTRAINT company_permission_overrides_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.company_permission_overrides ADD CONSTRAINT company_permission_overrides_feature_key_fkey FOREIGN KEY (feature_key) REFERENCES public.feature_flags(feature_key) ON DELETE CASCADE;
ALTER TABLE public.company_print_settings ADD CONSTRAINT company_print_settings_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.company_settings ADD CONSTRAINT company_settings_cash_account_id_fkey FOREIGN KEY (cash_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.company_settings ADD CONSTRAINT company_settings_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.company_settings ADD CONSTRAINT company_settings_default_branch_id_fkey FOREIGN KEY (default_branch_id) REFERENCES public.branches(id) ON DELETE SET NULL;
ALTER TABLE public.company_settings ADD CONSTRAINT company_settings_default_warehouse_id_fkey FOREIGN KEY (default_warehouse_id) REFERENCES public.warehouses(id) ON DELETE SET NULL;
ALTER TABLE public.company_settings ADD CONSTRAINT company_settings_inventory_account_id_fkey FOREIGN KEY (inventory_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.company_settings ADD CONSTRAINT company_settings_payables_account_id_fkey FOREIGN KEY (payables_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.company_settings ADD CONSTRAINT company_settings_purchases_account_id_fkey FOREIGN KEY (purchases_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.company_settings ADD CONSTRAINT company_settings_receivables_account_id_fkey FOREIGN KEY (receivables_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.company_settings ADD CONSTRAINT company_settings_sales_account_id_fkey FOREIGN KEY (sales_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.company_settings ADD CONSTRAINT company_settings_vat_account_id_fkey FOREIGN KEY (vat_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.contacts ADD CONSTRAINT contacts_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.contacts ADD CONSTRAINT contacts_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.cost_centers ADD CONSTRAINT cost_centers_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.cost_centers ADD CONSTRAINT cost_centers_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.cost_centers(id) ON DELETE SET NULL;
ALTER TABLE public.delivery_account_settings ADD CONSTRAINT delivery_account_settings_bank_account_id_fkey FOREIGN KEY (bank_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.delivery_account_settings ADD CONSTRAINT delivery_account_settings_cash_account_id_fkey FOREIGN KEY (cash_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.delivery_account_settings ADD CONSTRAINT delivery_account_settings_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.delivery_account_settings ADD CONSTRAINT delivery_account_settings_customer_receivable_account_id_fkey FOREIGN KEY (customer_receivable_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.delivery_account_settings ADD CONSTRAINT delivery_account_settings_delivery_commission_expense_acco_fkey FOREIGN KEY (delivery_commission_expense_account_id) REFERENCES public.accounts(id) ON DELETE CASCADE;
ALTER TABLE public.delivery_account_settings ADD CONSTRAINT delivery_account_settings_delivery_revenue_account_id_fkey FOREIGN KEY (delivery_revenue_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.delivery_account_settings ADD CONSTRAINT delivery_account_settings_driver_payable_account_id_fkey FOREIGN KEY (driver_payable_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.delivery_account_settings ADD CONSTRAINT delivery_account_settings_sales_return_account_id_fkey FOREIGN KEY (sales_return_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.delivery_account_settings ADD CONSTRAINT delivery_account_settings_sales_revenue_account_id_fkey FOREIGN KEY (sales_revenue_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.delivery_areas ADD CONSTRAINT delivery_areas_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id) ON DELETE SET NULL;
ALTER TABLE public.delivery_areas ADD CONSTRAINT delivery_areas_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.delivery_drivers ADD CONSTRAINT delivery_drivers_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id) ON DELETE SET NULL;
ALTER TABLE public.delivery_drivers ADD CONSTRAINT delivery_drivers_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.delivery_orders ADD CONSTRAINT delivery_orders_area_id_fkey FOREIGN KEY (area_id) REFERENCES public.delivery_areas(id) ON DELETE CASCADE;
ALTER TABLE public.delivery_orders ADD CONSTRAINT delivery_orders_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id) ON DELETE SET NULL;
ALTER TABLE public.delivery_orders ADD CONSTRAINT delivery_orders_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.delivery_orders ADD CONSTRAINT delivery_orders_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.delivery_drivers(id) ON DELETE CASCADE;
ALTER TABLE public.delivery_orders ADD CONSTRAINT delivery_orders_journal_entry_id_fkey FOREIGN KEY (journal_entry_id) REFERENCES public.journal_entries(id) ON DELETE SET NULL;
ALTER TABLE public.doctors ADD CONSTRAINT doctors_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.fiscal_periods ADD CONSTRAINT fiscal_periods_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.fiscal_year_audit_log ADD CONSTRAINT fiscal_year_audit_log_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.fiscal_year_audit_log ADD CONSTRAINT fiscal_year_audit_log_fiscal_year_id_fkey FOREIGN KEY (fiscal_year_id) REFERENCES public.fiscal_periods(id) ON DELETE CASCADE;
ALTER TABLE public.fixed_asset_account_settings ADD CONSTRAINT fixed_asset_account_settings_accumulated_depreciation_acco_fkey FOREIGN KEY (accumulated_depreciation_account_id) REFERENCES public.accounts(id) ON DELETE CASCADE;
ALTER TABLE public.fixed_asset_account_settings ADD CONSTRAINT fixed_asset_account_settings_asset_account_id_fkey FOREIGN KEY (asset_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.fixed_asset_account_settings ADD CONSTRAINT fixed_asset_account_settings_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.fixed_asset_account_settings ADD CONSTRAINT fixed_asset_account_settings_depreciation_expense_account__fkey FOREIGN KEY (depreciation_expense_account_id) REFERENCES public.accounts(id) ON DELETE CASCADE;
ALTER TABLE public.fixed_asset_account_settings ADD CONSTRAINT fixed_asset_account_settings_disposal_gain_account_id_fkey FOREIGN KEY (disposal_gain_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.fixed_asset_account_settings ADD CONSTRAINT fixed_asset_account_settings_disposal_loss_account_id_fkey FOREIGN KEY (disposal_loss_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.fixed_asset_account_settings ADD CONSTRAINT fixed_asset_account_settings_maintenance_expense_account_i_fkey FOREIGN KEY (maintenance_expense_account_id) REFERENCES public.accounts(id) ON DELETE CASCADE;
ALTER TABLE public.fixed_assets ADD CONSTRAINT fixed_assets_accumulated_depreciation_account_id_fkey FOREIGN KEY (accumulated_depreciation_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.fixed_assets ADD CONSTRAINT fixed_assets_asset_account_id_fkey FOREIGN KEY (asset_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.fixed_assets ADD CONSTRAINT fixed_assets_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id) ON DELETE SET NULL;
ALTER TABLE public.fixed_assets ADD CONSTRAINT fixed_assets_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.asset_categories(id) ON DELETE CASCADE;
ALTER TABLE public.fixed_assets ADD CONSTRAINT fixed_assets_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.fixed_assets ADD CONSTRAINT fixed_assets_depreciation_account_id_fkey FOREIGN KEY (depreciation_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.fixed_assets ADD CONSTRAINT fixed_assets_supplier_contact_id_fkey FOREIGN KEY (supplier_contact_id) REFERENCES public.contacts(id) ON DELETE SET NULL;
ALTER TABLE public.fuel_customers ADD CONSTRAINT fuel_customers_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.fuel_customers ADD CONSTRAINT fuel_customers_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.fuel_message_logs ADD CONSTRAINT fuel_message_logs_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.fuel_message_logs ADD CONSTRAINT fuel_message_logs_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.fuel_customers(id) ON DELETE CASCADE;
ALTER TABLE public.fuel_prices ADD CONSTRAINT fuel_prices_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.fuel_pumps ADD CONSTRAINT fuel_pumps_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.fuel_pumps ADD CONSTRAINT fuel_pumps_tank_id_fkey FOREIGN KEY (tank_id) REFERENCES public.fuel_tanks(id) ON DELETE CASCADE;
ALTER TABLE public.fuel_sales ADD CONSTRAINT fuel_sales_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.fuel_sales ADD CONSTRAINT fuel_sales_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.fuel_customers(id) ON DELETE CASCADE;
ALTER TABLE public.fuel_sales ADD CONSTRAINT fuel_sales_journal_entry_id_fkey FOREIGN KEY (journal_entry_id) REFERENCES public.journal_entries(id) ON DELETE SET NULL;
ALTER TABLE public.fuel_sales ADD CONSTRAINT fuel_sales_pump_id_fkey FOREIGN KEY (pump_id) REFERENCES public.fuel_pumps(id) ON DELETE CASCADE;
ALTER TABLE public.fuel_station_account_settings ADD CONSTRAINT fuel_station_account_settings_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.fuel_station_account_settings ADD CONSTRAINT fuel_station_account_settings_fuel_bank_account_id_fkey FOREIGN KEY (fuel_bank_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.fuel_station_account_settings ADD CONSTRAINT fuel_station_account_settings_fuel_cash_account_id_fkey FOREIGN KEY (fuel_cash_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.fuel_station_account_settings ADD CONSTRAINT fuel_station_account_settings_fuel_cogs_account_id_fkey FOREIGN KEY (fuel_cogs_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.fuel_station_account_settings ADD CONSTRAINT fuel_station_account_settings_fuel_customer_receivable_acc_fkey FOREIGN KEY (fuel_customer_receivable_account_id) REFERENCES public.accounts(id) ON DELETE CASCADE;
ALTER TABLE public.fuel_station_account_settings ADD CONSTRAINT fuel_station_account_settings_fuel_inventory_account_id_fkey FOREIGN KEY (fuel_inventory_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.fuel_station_account_settings ADD CONSTRAINT fuel_station_account_settings_fuel_sales_revenue_account_i_fkey FOREIGN KEY (fuel_sales_revenue_account_id) REFERENCES public.accounts(id) ON DELETE CASCADE;
ALTER TABLE public.fuel_station_account_settings ADD CONSTRAINT fuel_station_account_settings_fuel_sales_tax_account_id_fkey FOREIGN KEY (fuel_sales_tax_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.fuel_station_account_settings ADD CONSTRAINT fuel_station_account_settings_fuel_supplier_payable_accoun_fkey FOREIGN KEY (fuel_supplier_payable_account_id) REFERENCES public.accounts(id) ON DELETE CASCADE;
ALTER TABLE public.fuel_station_account_settings ADD CONSTRAINT fuel_station_account_settings_fuel_wallet_liability_accoun_fkey FOREIGN KEY (fuel_wallet_liability_account_id) REFERENCES public.accounts(id) ON DELETE CASCADE;
ALTER TABLE public.fuel_tank_refills ADD CONSTRAINT fuel_tank_refills_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.fuel_tank_refills ADD CONSTRAINT fuel_tank_refills_journal_entry_id_fkey FOREIGN KEY (journal_entry_id) REFERENCES public.journal_entries(id) ON DELETE SET NULL;
ALTER TABLE public.fuel_tank_refills ADD CONSTRAINT fuel_tank_refills_tank_id_fkey FOREIGN KEY (tank_id) REFERENCES public.fuel_tanks(id) ON DELETE CASCADE;
ALTER TABLE public.fuel_tanks ADD CONSTRAINT fuel_tanks_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id) ON DELETE SET NULL;
ALTER TABLE public.fuel_tanks ADD CONSTRAINT fuel_tanks_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.fuel_wallet_transactions ADD CONSTRAINT fuel_wallet_transactions_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.fuel_wallet_transactions ADD CONSTRAINT fuel_wallet_transactions_journal_entry_id_fkey FOREIGN KEY (journal_entry_id) REFERENCES public.journal_entries(id) ON DELETE SET NULL;
ALTER TABLE public.fuel_wallet_transactions ADD CONSTRAINT fuel_wallet_transactions_wallet_id_fkey FOREIGN KEY (wallet_id) REFERENCES public.fuel_wallets(id) ON DELETE CASCADE;
ALTER TABLE public.fuel_wallets ADD CONSTRAINT fuel_wallets_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.fuel_wallets ADD CONSTRAINT fuel_wallets_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.fuel_customers(id) ON DELETE CASCADE;
ALTER TABLE public.gold_account_settings ADD CONSTRAINT gold_account_settings_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.gold_account_settings ADD CONSTRAINT gold_account_settings_gold_cogs_account_id_fkey FOREIGN KEY (gold_cogs_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.gold_account_settings ADD CONSTRAINT gold_account_settings_gold_inventory_account_id_fkey FOREIGN KEY (gold_inventory_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.gold_account_settings ADD CONSTRAINT gold_account_settings_gold_payable_account_id_fkey FOREIGN KEY (gold_payable_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.gold_account_settings ADD CONSTRAINT gold_account_settings_gold_purchase_expense_account_id_fkey FOREIGN KEY (gold_purchase_expense_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.gold_account_settings ADD CONSTRAINT gold_account_settings_gold_purchase_tax_account_id_fkey FOREIGN KEY (gold_purchase_tax_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.gold_account_settings ADD CONSTRAINT gold_account_settings_gold_receivable_account_id_fkey FOREIGN KEY (gold_receivable_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.gold_account_settings ADD CONSTRAINT gold_account_settings_gold_sales_revenue_account_id_fkey FOREIGN KEY (gold_sales_revenue_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.gold_account_settings ADD CONSTRAINT gold_account_settings_gold_sales_tax_account_id_fkey FOREIGN KEY (gold_sales_tax_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.gold_account_settings ADD CONSTRAINT gold_account_settings_making_cost_revenue_account_id_fkey FOREIGN KEY (making_cost_revenue_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.gold_account_settings ADD CONSTRAINT gold_account_settings_stone_cost_account_id_fkey FOREIGN KEY (stone_cost_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.gold_items ADD CONSTRAINT gold_items_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.gold_items ADD CONSTRAINT gold_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;
ALTER TABLE public.gold_price_settings ADD CONSTRAINT gold_price_settings_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.gold_purchase_invoice_items ADD CONSTRAINT gold_purchase_invoice_items_gold_item_id_fkey FOREIGN KEY (gold_item_id) REFERENCES public.gold_items(id) ON DELETE CASCADE;
ALTER TABLE public.gold_purchase_invoice_items ADD CONSTRAINT gold_purchase_invoice_items_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.gold_purchase_invoices(id) ON DELETE CASCADE;
ALTER TABLE public.gold_purchase_invoices ADD CONSTRAINT gold_purchase_invoices_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id) ON DELETE SET NULL;
ALTER TABLE public.gold_purchase_invoices ADD CONSTRAINT gold_purchase_invoices_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.gold_purchase_invoices ADD CONSTRAINT gold_purchase_invoices_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.contacts(id) ON DELETE SET NULL;
ALTER TABLE public.gold_purchase_invoices ADD CONSTRAINT gold_purchase_invoices_journal_entry_id_fkey FOREIGN KEY (journal_entry_id) REFERENCES public.journal_entries(id) ON DELETE SET NULL;
ALTER TABLE public.gold_sales_invoice_items ADD CONSTRAINT gold_sales_invoice_items_gold_item_id_fkey FOREIGN KEY (gold_item_id) REFERENCES public.gold_items(id) ON DELETE CASCADE;
ALTER TABLE public.gold_sales_invoice_items ADD CONSTRAINT gold_sales_invoice_items_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.gold_sales_invoices(id) ON DELETE CASCADE;
ALTER TABLE public.gold_sales_invoices ADD CONSTRAINT gold_sales_invoices_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id) ON DELETE SET NULL;
ALTER TABLE public.gold_sales_invoices ADD CONSTRAINT gold_sales_invoices_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.gold_sales_invoices ADD CONSTRAINT gold_sales_invoices_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.contacts(id) ON DELETE SET NULL;
ALTER TABLE public.gold_sales_invoices ADD CONSTRAINT gold_sales_invoices_journal_entry_id_fkey FOREIGN KEY (journal_entry_id) REFERENCES public.journal_entries(id) ON DELETE SET NULL;
ALTER TABLE public.hr_account_settings ADD CONSTRAINT hr_account_settings_bank_account_id_fkey FOREIGN KEY (bank_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.hr_account_settings ADD CONSTRAINT hr_account_settings_cash_account_id_fkey FOREIGN KEY (cash_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.hr_account_settings ADD CONSTRAINT hr_account_settings_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.hr_account_settings ADD CONSTRAINT hr_account_settings_employee_advances_account_id_fkey FOREIGN KEY (employee_advances_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.hr_account_settings ADD CONSTRAINT hr_account_settings_eos_expense_account_id_fkey FOREIGN KEY (eos_expense_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.hr_account_settings ADD CONSTRAINT hr_account_settings_eos_provision_account_id_fkey FOREIGN KEY (eos_provision_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.hr_account_settings ADD CONSTRAINT hr_account_settings_housing_expense_account_id_fkey FOREIGN KEY (housing_expense_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.hr_account_settings ADD CONSTRAINT hr_account_settings_loan_receivable_account_id_fkey FOREIGN KEY (loan_receivable_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.hr_account_settings ADD CONSTRAINT hr_account_settings_other_allowance_account_id_fkey FOREIGN KEY (other_allowance_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.hr_account_settings ADD CONSTRAINT hr_account_settings_penalties_revenue_account_id_fkey FOREIGN KEY (penalties_revenue_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.hr_account_settings ADD CONSTRAINT hr_account_settings_rewards_expense_account_id_fkey FOREIGN KEY (rewards_expense_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.hr_account_settings ADD CONSTRAINT hr_account_settings_salary_expense_account_id_fkey FOREIGN KEY (salary_expense_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.hr_account_settings ADD CONSTRAINT hr_account_settings_salary_payable_account_id_fkey FOREIGN KEY (salary_payable_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.hr_account_settings ADD CONSTRAINT hr_account_settings_social_insurance_expense_account_id_fkey FOREIGN KEY (social_insurance_expense_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.hr_account_settings ADD CONSTRAINT hr_account_settings_social_insurance_payable_account_id_fkey FOREIGN KEY (social_insurance_payable_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.hr_account_settings ADD CONSTRAINT hr_account_settings_transport_expense_account_id_fkey FOREIGN KEY (transport_expense_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.hr_attendance ADD CONSTRAINT hr_attendance_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.hr_attendance ADD CONSTRAINT hr_attendance_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.hr_employees(id) ON DELETE CASCADE;
ALTER TABLE public.hr_deductions ADD CONSTRAINT hr_deductions_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.hr_deductions ADD CONSTRAINT hr_deductions_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.hr_employees(id) ON DELETE CASCADE;
ALTER TABLE public.hr_deductions ADD CONSTRAINT hr_deductions_journal_entry_id_fkey FOREIGN KEY (journal_entry_id) REFERENCES public.journal_entries(id) ON DELETE SET NULL;
ALTER TABLE public.hr_deductions ADD CONSTRAINT hr_deductions_payroll_run_id_fkey FOREIGN KEY (payroll_run_id) REFERENCES public.hr_payroll_runs(id) ON DELETE CASCADE;
ALTER TABLE public.hr_deductions ADD CONSTRAINT hr_deductions_penalty_rule_id_fkey FOREIGN KEY (penalty_rule_id) REFERENCES public.hr_penalty_rules(id) ON DELETE CASCADE;
ALTER TABLE public.hr_departments ADD CONSTRAINT hr_departments_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.hr_employees ADD CONSTRAINT hr_employees_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.hr_employees ADD CONSTRAINT hr_employees_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.hr_employees ADD CONSTRAINT hr_employees_cost_center_id_fkey FOREIGN KEY (cost_center_id) REFERENCES public.cost_centers(id) ON DELETE SET NULL;
ALTER TABLE public.hr_employees ADD CONSTRAINT hr_employees_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.hr_departments(id) ON DELETE CASCADE;
ALTER TABLE public.hr_employees ADD CONSTRAINT hr_employees_work_shift_id_fkey FOREIGN KEY (work_shift_id) REFERENCES public.hr_work_shifts(id) ON DELETE CASCADE;
ALTER TABLE public.hr_leave_balances ADD CONSTRAINT hr_leave_balances_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.hr_leave_balances ADD CONSTRAINT hr_leave_balances_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.hr_employees(id) ON DELETE CASCADE;
ALTER TABLE public.hr_leave_policies ADD CONSTRAINT hr_leave_policies_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.hr_leaves ADD CONSTRAINT hr_leaves_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.hr_leaves ADD CONSTRAINT hr_leaves_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.hr_employees(id) ON DELETE CASCADE;
ALTER TABLE public.hr_loans ADD CONSTRAINT hr_loans_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.hr_loans ADD CONSTRAINT hr_loans_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.hr_employees(id) ON DELETE CASCADE;
ALTER TABLE public.hr_payroll_items ADD CONSTRAINT hr_payroll_items_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.hr_employees(id) ON DELETE CASCADE;
ALTER TABLE public.hr_payroll_items ADD CONSTRAINT hr_payroll_items_payroll_run_id_fkey FOREIGN KEY (payroll_run_id) REFERENCES public.hr_payroll_runs(id) ON DELETE CASCADE;
ALTER TABLE public.hr_payroll_payment_items ADD CONSTRAINT hr_payroll_payment_items_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.hr_employees(id) ON DELETE CASCADE;
ALTER TABLE public.hr_payroll_payment_items ADD CONSTRAINT hr_payroll_payment_items_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES public.hr_payroll_payments(id) ON DELETE CASCADE;
ALTER TABLE public.hr_payroll_payment_items ADD CONSTRAINT hr_payroll_payment_items_payroll_item_id_fkey FOREIGN KEY (payroll_item_id) REFERENCES public.hr_payroll_items(id) ON DELETE CASCADE;
ALTER TABLE public.hr_payroll_payments ADD CONSTRAINT hr_payroll_payments_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.hr_payroll_payments ADD CONSTRAINT hr_payroll_payments_journal_entry_id_fkey FOREIGN KEY (journal_entry_id) REFERENCES public.journal_entries(id) ON DELETE SET NULL;
ALTER TABLE public.hr_payroll_payments ADD CONSTRAINT hr_payroll_payments_payment_method_id_fkey FOREIGN KEY (payment_method_id) REFERENCES public.payment_methods(id) ON DELETE CASCADE;
ALTER TABLE public.hr_payroll_payments ADD CONSTRAINT hr_payroll_payments_payroll_run_id_fkey FOREIGN KEY (payroll_run_id) REFERENCES public.hr_payroll_runs(id) ON DELETE CASCADE;
ALTER TABLE public.hr_payroll_runs ADD CONSTRAINT hr_payroll_runs_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.hr_penalty_rules ADD CONSTRAINT hr_penalty_rules_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.hr_work_shifts ADD CONSTRAINT hr_work_shifts_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.internal_consumption_items ADD CONSTRAINT internal_consumption_items_consumption_id_fkey FOREIGN KEY (consumption_id) REFERENCES public.internal_consumptions(id) ON DELETE CASCADE;
ALTER TABLE public.internal_consumption_items ADD CONSTRAINT internal_consumption_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;
ALTER TABLE public.internal_consumptions ADD CONSTRAINT internal_consumptions_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id) ON DELETE SET NULL;
ALTER TABLE public.internal_consumptions ADD CONSTRAINT internal_consumptions_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.invitations ADD CONSTRAINT invitations_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.invoice_items ADD CONSTRAINT invoice_items_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id) ON DELETE CASCADE;
ALTER TABLE public.invoice_items ADD CONSTRAINT invoice_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;
ALTER TABLE public.invoice_payments ADD CONSTRAINT invoice_payments_bank_account_id_fkey FOREIGN KEY (bank_account_id) REFERENCES public.bank_accounts(id) ON DELETE SET NULL;
ALTER TABLE public.invoice_payments ADD CONSTRAINT invoice_payments_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.invoice_payments ADD CONSTRAINT invoice_payments_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id) ON DELETE SET NULL;
ALTER TABLE public.invoice_payments ADD CONSTRAINT invoice_payments_journal_entry_id_fkey FOREIGN KEY (journal_entry_id) REFERENCES public.journal_entries(id) ON DELETE SET NULL;
ALTER TABLE public.invoice_payments ADD CONSTRAINT invoice_payments_treasury_transaction_id_fkey FOREIGN KEY (treasury_transaction_id) REFERENCES public.treasury_transactions(id) ON DELETE SET NULL;
ALTER TABLE public.invoices ADD CONSTRAINT invoices_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id) ON DELETE SET NULL;
ALTER TABLE public.invoices ADD CONSTRAINT invoices_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.invoices ADD CONSTRAINT invoices_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.contacts(id) ON DELETE SET NULL;
ALTER TABLE public.invoices ADD CONSTRAINT invoices_journal_entry_id_fkey FOREIGN KEY (journal_entry_id) REFERENCES public.journal_entries(id) ON DELETE SET NULL;
ALTER TABLE public.invoices ADD CONSTRAINT invoices_warehouse_id_fkey FOREIGN KEY (warehouse_id) REFERENCES public.warehouses(id) ON DELETE SET NULL;
ALTER TABLE public.journal_entries ADD CONSTRAINT journal_entries_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.journal_entry_lines ADD CONSTRAINT journal_entry_lines_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.journal_entry_lines ADD CONSTRAINT journal_entry_lines_cost_center_id_fkey FOREIGN KEY (cost_center_id) REFERENCES public.cost_centers(id) ON DELETE SET NULL;
ALTER TABLE public.journal_entry_lines ADD CONSTRAINT journal_entry_lines_entry_id_fkey FOREIGN KEY (entry_id) REFERENCES public.journal_entries(id) ON DELETE CASCADE;
ALTER TABLE public.manufacturing_orders ADD CONSTRAINT manufacturing_orders_bom_id_fkey FOREIGN KEY (bom_id) REFERENCES public.bill_of_materials(id) ON DELETE CASCADE;
ALTER TABLE public.manufacturing_orders ADD CONSTRAINT manufacturing_orders_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id) ON DELETE SET NULL;
ALTER TABLE public.manufacturing_orders ADD CONSTRAINT manufacturing_orders_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.manufacturing_orders ADD CONSTRAINT manufacturing_orders_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;
ALTER TABLE public.opening_balances ADD CONSTRAINT opening_balances_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.opening_balances ADD CONSTRAINT opening_balances_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.opening_balances ADD CONSTRAINT opening_balances_fiscal_year_id_fkey FOREIGN KEY (fiscal_year_id) REFERENCES public.fiscal_periods(id) ON DELETE CASCADE;
ALTER TABLE public.patients ADD CONSTRAINT patients_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.patients ADD CONSTRAINT patients_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.payment_methods ADD CONSTRAINT payment_methods_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.payment_methods ADD CONSTRAINT payment_methods_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.payments ADD CONSTRAINT payments_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.payments ADD CONSTRAINT payments_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.subscription_plans(id) ON DELETE CASCADE;
ALTER TABLE public.payments ADD CONSTRAINT payments_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.subscriptions(id) ON DELETE CASCADE;
ALTER TABLE public.plan_feature_permissions ADD CONSTRAINT plan_feature_permissions_feature_key_fkey FOREIGN KEY (feature_key) REFERENCES public.feature_flags(feature_key) ON DELETE CASCADE;
ALTER TABLE public.plan_feature_permissions ADD CONSTRAINT plan_feature_permissions_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.subscription_plans(id) ON DELETE CASCADE;
ALTER TABLE public.plan_permission_bounds ADD CONSTRAINT plan_permission_bounds_permission_id_fkey FOREIGN KEY (permission_id) REFERENCES public.rbac_permissions(id) ON DELETE CASCADE;
ALTER TABLE public.plan_permission_bounds ADD CONSTRAINT plan_permission_bounds_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.subscription_plans(id) ON DELETE CASCADE;
ALTER TABLE public.plan_screens ADD CONSTRAINT plan_screens_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.subscription_plans(id) ON DELETE CASCADE;
ALTER TABLE public.plan_screens ADD CONSTRAINT plan_screens_screen_id_fkey FOREIGN KEY (screen_id) REFERENCES public.system_screens(id) ON DELETE CASCADE;
ALTER TABLE public.pos_account_settings ADD CONSTRAINT pos_account_settings_bank_transfer_account_id_fkey FOREIGN KEY (bank_transfer_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.pos_account_settings ADD CONSTRAINT pos_account_settings_card_account_id_fkey FOREIGN KEY (card_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.pos_account_settings ADD CONSTRAINT pos_account_settings_cash_account_id_fkey FOREIGN KEY (cash_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.pos_account_settings ADD CONSTRAINT pos_account_settings_cogs_account_id_fkey FOREIGN KEY (cogs_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.pos_account_settings ADD CONSTRAINT pos_account_settings_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.pos_account_settings ADD CONSTRAINT pos_account_settings_coupon_expense_account_id_fkey FOREIGN KEY (coupon_expense_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.pos_account_settings ADD CONSTRAINT pos_account_settings_discount_account_id_fkey FOREIGN KEY (discount_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.pos_account_settings ADD CONSTRAINT pos_account_settings_inventory_account_id_fkey FOREIGN KEY (inventory_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.pos_account_settings ADD CONSTRAINT pos_account_settings_refund_account_id_fkey FOREIGN KEY (refund_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.pos_account_settings ADD CONSTRAINT pos_account_settings_sales_revenue_account_id_fkey FOREIGN KEY (sales_revenue_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.pos_account_settings ADD CONSTRAINT pos_account_settings_sales_tax_account_id_fkey FOREIGN KEY (sales_tax_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.pos_account_settings ADD CONSTRAINT pos_account_settings_tips_revenue_account_id_fkey FOREIGN KEY (tips_revenue_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.pos_activity_log ADD CONSTRAINT pos_activity_log_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.pos_activity_log ADD CONSTRAINT pos_activity_log_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.pos_sessions(id) ON DELETE SET NULL;
ALTER TABLE public.pos_api_integrations ADD CONSTRAINT pos_api_integrations_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id) ON DELETE SET NULL;
ALTER TABLE public.pos_api_integrations ADD CONSTRAINT pos_api_integrations_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.pos_api_logs ADD CONSTRAINT pos_api_logs_integration_id_fkey FOREIGN KEY (integration_id) REFERENCES public.pos_api_integrations(id) ON DELETE CASCADE;
ALTER TABLE public.pos_api_logs ADD CONSTRAINT pos_api_logs_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.pos_api_orders(id) ON DELETE CASCADE;
ALTER TABLE public.pos_api_orders ADD CONSTRAINT pos_api_orders_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.pos_api_orders ADD CONSTRAINT pos_api_orders_integration_id_fkey FOREIGN KEY (integration_id) REFERENCES public.pos_api_integrations(id) ON DELETE CASCADE;
ALTER TABLE public.pos_api_orders ADD CONSTRAINT pos_api_orders_pos_transaction_id_fkey FOREIGN KEY (pos_transaction_id) REFERENCES public.pos_transactions(id) ON DELETE CASCADE;
ALTER TABLE public.pos_coupons ADD CONSTRAINT pos_coupons_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.pos_menu_items ADD CONSTRAINT pos_menu_items_menu_id_fkey FOREIGN KEY (menu_id) REFERENCES public.pos_menus(id) ON DELETE CASCADE;
ALTER TABLE public.pos_menu_items ADD CONSTRAINT pos_menu_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;
ALTER TABLE public.pos_menu_prices ADD CONSTRAINT pos_menu_prices_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.pos_menu_prices ADD CONSTRAINT pos_menu_prices_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;
ALTER TABLE public.pos_menus ADD CONSTRAINT pos_menus_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id) ON DELETE SET NULL;
ALTER TABLE public.pos_menus ADD CONSTRAINT pos_menus_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.pos_promotion_products ADD CONSTRAINT pos_promotion_products_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.pos_promotion_products ADD CONSTRAINT pos_promotion_products_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;
ALTER TABLE public.pos_promotion_products ADD CONSTRAINT pos_promotion_products_promotion_id_fkey FOREIGN KEY (promotion_id) REFERENCES public.pos_promotions(id) ON DELETE CASCADE;
ALTER TABLE public.pos_promotions ADD CONSTRAINT pos_promotions_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.pos_reservations ADD CONSTRAINT pos_reservations_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id) ON DELETE SET NULL;
ALTER TABLE public.pos_reservations ADD CONSTRAINT pos_reservations_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.pos_reservations ADD CONSTRAINT pos_reservations_table_id_fkey FOREIGN KEY (table_id) REFERENCES public.pos_tables(id) ON DELETE SET NULL;
ALTER TABLE public.pos_sales_targets ADD CONSTRAINT pos_sales_targets_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id) ON DELETE SET NULL;
ALTER TABLE public.pos_sales_targets ADD CONSTRAINT pos_sales_targets_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.pos_sales_targets ADD CONSTRAINT pos_sales_targets_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;
ALTER TABLE public.pos_sessions ADD CONSTRAINT pos_sessions_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id) ON DELETE SET NULL;
ALTER TABLE public.pos_sessions ADD CONSTRAINT pos_sessions_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.pos_sessions ADD CONSTRAINT pos_sessions_terminal_id_fkey FOREIGN KEY (terminal_id) REFERENCES public.pos_terminals(id) ON DELETE SET NULL;
ALTER TABLE public.pos_tables ADD CONSTRAINT pos_tables_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id) ON DELETE SET NULL;
ALTER TABLE public.pos_tables ADD CONSTRAINT pos_tables_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.pos_terminals ADD CONSTRAINT pos_terminals_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id) ON DELETE SET NULL;
ALTER TABLE public.pos_terminals ADD CONSTRAINT pos_terminals_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.pos_transaction_items ADD CONSTRAINT pos_transaction_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;
ALTER TABLE public.pos_transaction_items ADD CONSTRAINT pos_transaction_items_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES public.pos_transactions(id) ON DELETE CASCADE;
ALTER TABLE public.pos_transactions ADD CONSTRAINT pos_transactions_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id) ON DELETE SET NULL;
ALTER TABLE public.pos_transactions ADD CONSTRAINT pos_transactions_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.pos_transactions ADD CONSTRAINT pos_transactions_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.contacts(id) ON DELETE SET NULL;
ALTER TABLE public.pos_transactions ADD CONSTRAINT pos_transactions_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id) ON DELETE SET NULL;
ALTER TABLE public.pos_transactions ADD CONSTRAINT pos_transactions_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.pos_sessions(id) ON DELETE SET NULL;
ALTER TABLE public.pos_transactions ADD CONSTRAINT pos_transactions_table_id_fkey FOREIGN KEY (table_id) REFERENCES public.pos_tables(id) ON DELETE SET NULL;
ALTER TABLE public.pos_transactions ADD CONSTRAINT pos_transactions_terminal_id_fkey FOREIGN KEY (terminal_id) REFERENCES public.pos_terminals(id) ON DELETE SET NULL;
ALTER TABLE public.pos_users ADD CONSTRAINT pos_users_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id) ON DELETE SET NULL;
ALTER TABLE public.pos_users ADD CONSTRAINT pos_users_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.prescription_items ADD CONSTRAINT prescription_items_prescription_id_fkey FOREIGN KEY (prescription_id) REFERENCES public.prescriptions(id) ON DELETE CASCADE;
ALTER TABLE public.prescriptions ADD CONSTRAINT prescriptions_appointment_id_fkey FOREIGN KEY (appointment_id) REFERENCES public.appointments(id) ON DELETE CASCADE;
ALTER TABLE public.prescriptions ADD CONSTRAINT prescriptions_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.prescriptions ADD CONSTRAINT prescriptions_doctor_id_fkey FOREIGN KEY (doctor_id) REFERENCES public.doctors(id) ON DELETE CASCADE;
ALTER TABLE public.prescriptions ADD CONSTRAINT prescriptions_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id) ON DELETE CASCADE;
ALTER TABLE public.price_list_items ADD CONSTRAINT price_list_items_price_list_id_fkey FOREIGN KEY (price_list_id) REFERENCES public.price_lists(id) ON DELETE CASCADE;
ALTER TABLE public.price_list_items ADD CONSTRAINT price_list_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;
ALTER TABLE public.price_lists ADD CONSTRAINT price_lists_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.product_car_compatibility ADD CONSTRAINT product_car_compatibility_car_model_id_fkey FOREIGN KEY (car_model_id) REFERENCES public.car_models(id) ON DELETE CASCADE;
ALTER TABLE public.product_car_compatibility ADD CONSTRAINT product_car_compatibility_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;
ALTER TABLE public.product_categories ADD CONSTRAINT product_categories_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.product_categories ADD CONSTRAINT product_categories_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.product_categories(id) ON DELETE SET NULL;
ALTER TABLE public.product_stock ADD CONSTRAINT product_stock_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;
ALTER TABLE public.product_stock ADD CONSTRAINT product_stock_warehouse_id_fkey FOREIGN KEY (warehouse_id) REFERENCES public.warehouses(id) ON DELETE SET NULL;
ALTER TABLE public.products ADD CONSTRAINT products_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.product_categories(id) ON DELETE CASCADE;
ALTER TABLE public.products ADD CONSTRAINT products_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.products ADD CONSTRAINT products_unit_id_fkey FOREIGN KEY (unit_id) REFERENCES public.units(id) ON DELETE CASCADE;
ALTER TABLE public.rbac_role_permissions ADD CONSTRAINT rbac_role_permissions_permission_id_fkey FOREIGN KEY (permission_id) REFERENCES public.rbac_permissions(id) ON DELETE CASCADE;
ALTER TABLE public.rbac_role_permissions ADD CONSTRAINT rbac_role_permissions_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.rbac_roles(id) ON DELETE CASCADE;
ALTER TABLE public.rbac_roles ADD CONSTRAINT rbac_roles_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.rbac_user_roles ADD CONSTRAINT rbac_user_roles_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.rbac_user_roles ADD CONSTRAINT rbac_user_roles_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.rbac_roles(id) ON DELETE CASCADE;
ALTER TABLE public.re_account_settings ADD CONSTRAINT re_account_settings_bank_account_id_fkey FOREIGN KEY (bank_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.re_account_settings ADD CONSTRAINT re_account_settings_cash_account_id_fkey FOREIGN KEY (cash_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.re_account_settings ADD CONSTRAINT re_account_settings_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.re_account_settings ADD CONSTRAINT re_account_settings_maintenance_expense_account_id_fkey FOREIGN KEY (maintenance_expense_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.re_account_settings ADD CONSTRAINT re_account_settings_rental_revenue_account_id_fkey FOREIGN KEY (rental_revenue_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.re_account_settings ADD CONSTRAINT re_account_settings_security_deposit_liability_account_id_fkey FOREIGN KEY (security_deposit_liability_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.re_account_settings ADD CONSTRAINT re_account_settings_tenant_receivable_account_id_fkey FOREIGN KEY (tenant_receivable_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.re_leases ADD CONSTRAINT re_leases_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.re_leases ADD CONSTRAINT re_leases_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.re_tenants(id) ON DELETE CASCADE;
ALTER TABLE public.re_leases ADD CONSTRAINT re_leases_unit_id_fkey FOREIGN KEY (unit_id) REFERENCES public.re_units(id) ON DELETE CASCADE;
ALTER TABLE public.re_maintenance_requests ADD CONSTRAINT re_maintenance_requests_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.re_maintenance_requests ADD CONSTRAINT re_maintenance_requests_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.re_tenants(id) ON DELETE CASCADE;
ALTER TABLE public.re_maintenance_requests ADD CONSTRAINT re_maintenance_requests_unit_id_fkey FOREIGN KEY (unit_id) REFERENCES public.re_units(id) ON DELETE CASCADE;
ALTER TABLE public.re_properties ADD CONSTRAINT re_properties_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.re_rent_invoices ADD CONSTRAINT re_rent_invoices_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.re_rent_invoices ADD CONSTRAINT re_rent_invoices_journal_entry_id_fkey FOREIGN KEY (journal_entry_id) REFERENCES public.journal_entries(id) ON DELETE SET NULL;
ALTER TABLE public.re_rent_invoices ADD CONSTRAINT re_rent_invoices_lease_id_fkey FOREIGN KEY (lease_id) REFERENCES public.re_leases(id) ON DELETE CASCADE;
ALTER TABLE public.re_rent_invoices ADD CONSTRAINT re_rent_invoices_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.re_tenants(id) ON DELETE CASCADE;
ALTER TABLE public.re_rent_invoices ADD CONSTRAINT re_rent_invoices_unit_id_fkey FOREIGN KEY (unit_id) REFERENCES public.re_units(id) ON DELETE CASCADE;
ALTER TABLE public.re_rent_payments ADD CONSTRAINT re_rent_payments_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.re_rent_payments ADD CONSTRAINT re_rent_payments_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.re_rent_invoices(id) ON DELETE SET NULL;
ALTER TABLE public.re_rent_payments ADD CONSTRAINT re_rent_payments_journal_entry_id_fkey FOREIGN KEY (journal_entry_id) REFERENCES public.journal_entries(id) ON DELETE SET NULL;
ALTER TABLE public.re_rent_payments ADD CONSTRAINT re_rent_payments_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.re_tenants(id) ON DELETE CASCADE;
ALTER TABLE public.re_tenants ADD CONSTRAINT re_tenants_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.re_units ADD CONSTRAINT re_units_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.re_units ADD CONSTRAINT re_units_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.re_properties(id) ON DELETE CASCADE;
ALTER TABLE public.stock_adjustment_items ADD CONSTRAINT stock_adjustment_items_adjustment_id_fkey FOREIGN KEY (adjustment_id) REFERENCES public.stock_adjustments(id) ON DELETE CASCADE;
ALTER TABLE public.stock_adjustment_items ADD CONSTRAINT stock_adjustment_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;
ALTER TABLE public.stock_adjustments ADD CONSTRAINT stock_adjustments_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id) ON DELETE SET NULL;
ALTER TABLE public.stock_adjustments ADD CONSTRAINT stock_adjustments_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.stock_count_lines ADD CONSTRAINT stock_count_lines_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;
ALTER TABLE public.stock_count_lines ADD CONSTRAINT stock_count_lines_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.stock_count_sessions(id) ON DELETE CASCADE;
ALTER TABLE public.stock_count_lines ADD CONSTRAINT stock_count_lines_warehouse_id_fkey FOREIGN KEY (warehouse_id) REFERENCES public.warehouses(id) ON DELETE SET NULL;
ALTER TABLE public.stock_count_sessions ADD CONSTRAINT stock_count_sessions_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.stock_count_sessions ADD CONSTRAINT stock_count_sessions_fiscal_year_id_fkey FOREIGN KEY (fiscal_year_id) REFERENCES public.fiscal_periods(id) ON DELETE CASCADE;
ALTER TABLE public.stock_movements ADD CONSTRAINT stock_movements_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.stock_movements ADD CONSTRAINT stock_movements_from_warehouse_id_fkey FOREIGN KEY (from_warehouse_id) REFERENCES public.warehouses(id) ON DELETE SET NULL;
ALTER TABLE public.stock_movements ADD CONSTRAINT stock_movements_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;
ALTER TABLE public.stock_movements ADD CONSTRAINT stock_movements_warehouse_id_fkey FOREIGN KEY (warehouse_id) REFERENCES public.warehouses(id) ON DELETE SET NULL;
ALTER TABLE public.stock_transfer_items ADD CONSTRAINT stock_transfer_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;
ALTER TABLE public.stock_transfer_items ADD CONSTRAINT stock_transfer_items_transfer_id_fkey FOREIGN KEY (transfer_id) REFERENCES public.stock_transfers(id) ON DELETE CASCADE;
ALTER TABLE public.stock_transfers ADD CONSTRAINT stock_transfers_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.stock_transfers ADD CONSTRAINT stock_transfers_from_branch_id_fkey FOREIGN KEY (from_branch_id) REFERENCES public.branches(id) ON DELETE SET NULL;
ALTER TABLE public.stock_transfers ADD CONSTRAINT stock_transfers_to_branch_id_fkey FOREIGN KEY (to_branch_id) REFERENCES public.branches(id) ON DELETE SET NULL;
ALTER TABLE public.subscriptions ADD CONSTRAINT subscriptions_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.subscriptions ADD CONSTRAINT subscriptions_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.subscription_plans(id) ON DELETE CASCADE;
ALTER TABLE public.treasury_transactions ADD CONSTRAINT treasury_transactions_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.treasury_transactions ADD CONSTRAINT treasury_transactions_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.treasury_transactions ADD CONSTRAINT treasury_transactions_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.contacts(id) ON DELETE SET NULL;
ALTER TABLE public.treasury_transactions ADD CONSTRAINT treasury_transactions_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id) ON DELETE SET NULL;
ALTER TABLE public.treasury_transactions ADD CONSTRAINT treasury_transactions_journal_entry_id_fkey FOREIGN KEY (journal_entry_id) REFERENCES public.journal_entries(id) ON DELETE SET NULL;
ALTER TABLE public.treasury_transactions ADD CONSTRAINT treasury_transactions_transfer_account_id_fkey FOREIGN KEY (transfer_account_id) REFERENCES public.accounts(id) ON DELETE SET NULL;
ALTER TABLE public.units ADD CONSTRAINT units_base_unit_id_fkey FOREIGN KEY (base_unit_id) REFERENCES public.units(id) ON DELETE CASCADE;
ALTER TABLE public.units ADD CONSTRAINT units_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.usage_tracking ADD CONSTRAINT usage_tracking_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.vertical_screens ADD CONSTRAINT vertical_screens_screen_id_fkey FOREIGN KEY (screen_id) REFERENCES public.system_screens(id) ON DELETE CASCADE;
ALTER TABLE public.vertical_screens ADD CONSTRAINT vertical_screens_vertical_id_fkey FOREIGN KEY (vertical_id) REFERENCES public.business_verticals(id) ON DELETE CASCADE;
ALTER TABLE public.warehouses ADD CONSTRAINT warehouses_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id) ON DELETE SET NULL;
ALTER TABLE public.warehouses ADD CONSTRAINT warehouses_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.zatca_invoice_logs ADD CONSTRAINT zatca_invoice_logs_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.zatca_invoice_logs ADD CONSTRAINT zatca_invoice_logs_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id) ON DELETE SET NULL;
ALTER TABLE public.zatca_retry_queue ADD CONSTRAINT zatca_retry_queue_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;
ALTER TABLE public.zatca_retry_queue ADD CONSTRAINT zatca_retry_queue_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id) ON DELETE SET NULL;
ALTER TABLE public.zatca_settings ADD CONSTRAINT zatca_settings_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;

-- Total: 401 foreign key constraints
