import React from "react";
import { PrintSettings, CompanyInfo, PrintableDocument } from "./types";

interface PrintLayoutProps {
  settings: PrintSettings;
  company: CompanyInfo;
  document: PrintableDocument;
  isRTL?: boolean;
  children?: React.ReactNode;
}

const fontFamilies: Record<string, string> = {
  default: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
  serif: "Georgia, 'Times New Roman', serif",
  mono: "'Courier New', Courier, monospace",
  arabic: "'Noto Naskh Arabic', 'Traditional Arabic', serif",
};

export const PrintLayout: React.FC<PrintLayoutProps> = ({
  settings, company, document: doc, isRTL = true, children,
}) => {
  const style = settings.template_style;
  const dir = isRTL ? "rtl" : "ltr";
  const font = fontFamilies[settings.font_family] || fontFamilies.default;
  const pc = settings.primary_color || "#1e40af";

  return (
    <div
      className="print-layout"
      dir={dir}
      style={{
        fontFamily: font,
        paddingTop: `${settings.top_offset || 0}mm`,
        paddingBottom: `${settings.bottom_offset || 0}mm`,
        paddingLeft: `${settings.left_offset || 0}mm`,
        paddingRight: `${settings.right_offset || 0}mm`,
        maxWidth: "210mm",
        margin: "0 auto",
        background: "white",
        color: "#1a1a1a",
        fontSize: style === "minimal" ? "11px" : style === "government" ? "12px" : "13px",
        lineHeight: style === "minimal" ? "1.3" : "1.5",
      }}
    >
      {/* Letterhead */}
      {settings.letterhead_type === "uploaded" && settings.letterhead_file_url && (
        <div style={{ position: "absolute", top: 0, left: 0, right: 0, zIndex: -1, opacity: 0.15 }}>
          <img src={settings.letterhead_file_url} alt="" style={{ width: "100%", height: "auto" }} />
        </div>
      )}

      {/* Header */}
      <PrintHeader settings={settings} company={company} doc={doc} style={style} pc={pc} isRTL={isRTL} />

      {/* Document Body */}
      {doc.extraFields && doc.extraFields.length > 0 && (
        <div style={{
          display: "grid",
          gridTemplateColumns: "repeat(auto-fill, minmax(180px, 1fr))",
          gap: "8px",
          marginBottom: style === "minimal" ? "8px" : "16px",
          padding: style === "government" ? "8px" : "0",
          border: style === "government" ? `1px solid ${pc}` : "none",
          borderRadius: style === "modern" ? "6px" : "0",
          background: style === "government" ? "#f8fafc" : "transparent",
        }}>
          {doc.extraFields.map((f, i) => (
            <div key={i} style={{ padding: "4px 8px" }}>
              <span style={{ fontSize: "10px", color: "#666" }}>{f.label}</span>
              <div style={{ fontWeight: 600 }}>{f.value}</div>
            </div>
          ))}
        </div>
      )}

      {/* Table */}
      {doc.table && (
        <PrintTable table={doc.table} style={style} pc={pc} isRTL={isRTL} />
      )}

      {/* Custom children */}
      {children}

      {/* Notes */}
      {doc.notes && (
        <div style={{
          marginTop: "12px",
          padding: "8px 12px",
          background: "#f9fafb",
          borderRadius: style === "modern" ? "6px" : "0",
          fontSize: "11px",
          border: style === "classic" || style === "government" ? "1px solid #e5e7eb" : "none",
        }}>
          <strong>{isRTL ? "ملاحظات:" : "Notes:"}</strong> {doc.notes}
        </div>
      )}

      {/* Signature */}
      {settings.show_signature && settings.signature_url && (
        <div style={{
          marginTop: "40px",
          textAlign: isRTL ? "left" : "right",
        }}>
          <img src={settings.signature_url} alt="Signature" style={{ height: "60px", display: "inline-block" }} />
          <div style={{ fontSize: "10px", color: "#666", marginTop: "4px" }}>
            {isRTL ? "التوقيع" : "Signature"}
          </div>
        </div>
      )}

      {/* Footer */}
      {settings.show_footer && (
        <div style={{
          marginTop: "30px",
          paddingTop: "8px",
          borderTop: `2px solid ${pc}`,
          textAlign: "center",
          fontSize: "10px",
          color: "#666",
        }}>
          {settings.footer_text || (isRTL ? "تم إعداده بواسطة نظام نظام المحاسبي" : "Generated by Nizam Accounting System")}
        </div>
      )}
    </div>
  );
};

/* ─── Header ─── */
function PrintHeader({ settings, company, doc, style, pc, isRTL }: {
  settings: PrintSettings; company: CompanyInfo; doc: PrintableDocument;
  style: string; pc: string; isRTL: boolean;
}) {
  const headerBorder = style === "classic" ? `2px solid ${pc}` :
    style === "government" ? `3px double ${pc}` :
    style === "modern" ? "none" : "none";

  return (
    <div style={{
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      paddingTop: style === "modern" ? "16px" : style === "government" ? "12px" : "0",
      paddingBottom: style === "minimal" ? "6px" : style === "modern" ? "16px" : style === "government" ? "12px" : "12px",
      paddingLeft: style === "modern" ? "16px" : style === "government" ? "12px" : "0",
      paddingRight: style === "modern" ? "16px" : style === "government" ? "12px" : "0",
      marginBottom: style === "minimal" ? "8px" : "16px",
      borderBottom: headerBorder,
      background: style === "modern" ? `linear-gradient(135deg, ${pc}11, ${pc}05)` : "transparent",
      borderRadius: style === "modern" ? "8px" : "0",
    }}>
      {/* Company Info */}
      <div style={{ flex: 1 }}>
        <h2 style={{
          margin: 0,
          fontSize: style === "government" ? "18px" : style === "modern" ? "16px" : "15px",
          fontWeight: 700,
          color: style === "modern" ? pc : "#1a1a1a",
        }}>
          {isRTL ? company.name : (company.name_en || company.name)}
        </h2>
        {company.name_en && isRTL && (
          <p style={{ margin: "2px 0 0", fontSize: "12px", color: "#666" }}>{company.name_en}</p>
        )}
        {settings.show_tax_number && company.tax_number && (
          <p style={{ margin: "2px 0 0", fontSize: "10px", color: "#888" }}>
            {isRTL ? "الرقم الضريبي: " : "Tax No: "}{company.tax_number}
          </p>
        )}
        {settings.show_commercial_register && company.commercial_register && (
          <p style={{ margin: "2px 0 0", fontSize: "10px", color: "#888" }}>
            {isRTL ? "السجل التجاري: " : "CR: "}{company.commercial_register}
          </p>
        )}
        {company.address && (
          <p style={{ margin: "2px 0 0", fontSize: "10px", color: "#888" }}>{company.address}</p>
        )}
      </div>

      {/* Logo */}
      {settings.show_logo && company.logo_url && (
        <div style={{ marginInlineStart: "16px" }}>
          <img src={company.logo_url} alt="Logo" style={{
            height: style === "government" ? "70px" : "55px",
            objectFit: "contain",
          }} />
        </div>
      )}

      {/* Document Title */}
      <div style={{ textAlign: isRTL ? "left" : "right", flex: 1 }}>
        <h1 style={{
          margin: 0,
          fontSize: style === "government" ? "20px" : style === "modern" ? "18px" : "16px",
          fontWeight: 700,
          color: pc,
        }}>
          {doc.title}
        </h1>
        {doc.subtitle && (
          <p style={{ margin: "2px 0 0", fontSize: "11px", color: "#666" }}>{doc.subtitle}</p>
        )}
        {doc.number && (
          <p style={{ margin: "4px 0 0", fontSize: "12px", fontFamily: "monospace" }}>
            {isRTL ? "رقم: " : "#"}{doc.number}
          </p>
        )}
        {doc.date && (
          <p style={{ margin: "2px 0 0", fontSize: "11px", color: "#666" }}>
            {isRTL ? "التاريخ: " : "Date: "}{doc.date}
          </p>
        )}
      </div>
    </div>
  );
}

/* ─── Table ─── */
function PrintTable({ table, style, pc, isRTL }: {
  table: PrintableDocument["table"];
  style: string; pc: string; isRTL: boolean;
}) {
  if (!table) return null;

  const borderStyle = style === "classic" ? "1px solid #d1d5db" :
    style === "government" ? "1.5px solid #374151" :
    style === "modern" ? "1px solid #e5e7eb" :
    "none";

  return (
    <table style={{
      width: "100%",
      borderCollapse: "collapse",
      marginBottom: "12px",
    }}>
      <thead>
        <tr>
          {table.headers.map((h, i) => (
            <th key={i} style={{
              padding: style === "minimal" ? "4px 6px" : "8px 10px",
              textAlign: isRTL ? "right" : "left",
              border: borderStyle,
              background: style === "classic" ? "#f3f4f6" :
                style === "government" ? "#e5e7eb" :
                style === "modern" ? pc : "transparent",
              color: style === "modern" ? "white" : "#374151",
              fontSize: style === "minimal" ? "10px" : "11px",
              fontWeight: 700,
              borderBottom: style === "minimal" ? `2px solid ${pc}` : borderStyle,
            }}>
              {h}
            </th>
          ))}
        </tr>
      </thead>
      <tbody>
        {table.rows.map((row, ri) => (
          <tr key={ri}>
            {row.map((cell, ci) => (
              <td key={ci} style={{
                padding: style === "minimal" ? "3px 6px" : "6px 10px",
                border: style === "minimal" ? "none" : borderStyle,
                borderBottom: style === "minimal" ? "1px solid #f3f4f6" : borderStyle,
                fontSize: style === "minimal" ? "10px" : "12px",
                fontVariantNumeric: typeof cell === "number" ? "tabular-nums" : undefined,
                textAlign: typeof cell === "number" ? (isRTL ? "left" : "right") : (isRTL ? "right" : "left"),
              }}>
                {typeof cell === "number" ? cell.toLocaleString("en-US", { minimumFractionDigits: 2 }) : cell}
              </td>
            ))}
          </tr>
        ))}
        {table.totals && (
          <tr>
            {table.totals.map((cell, ci) => (
              <td key={ci} style={{
                padding: style === "minimal" ? "4px 6px" : "8px 10px",
                border: borderStyle,
                fontWeight: 700,
                fontSize: style === "minimal" ? "11px" : "13px",
                background: style === "classic" ? "#f9fafb" :
                  style === "government" ? "#e5e7eb" :
                  style === "modern" ? `${pc}11` : "transparent",
                borderTop: style === "minimal" ? `2px solid ${pc}` : borderStyle,
                textAlign: typeof cell === "number" ? (isRTL ? "left" : "right") : (isRTL ? "right" : "left"),
              }}>
                {typeof cell === "number" ? cell.toLocaleString("en-US", { minimumFractionDigits: 2 }) : cell}
              </td>
            ))}
          </tr>
        )}
      </tbody>
    </table>
  );
}

export default PrintLayout;
